ALTER TABLE tenants DROP COLUMN IF EXISTS branding;
ALTER TABLE rewards DROP COLUMN IF EXISTS flash_end;
ALTER TABLE rewards DROP COLUMN IF EXISTS flash_start;
ALTER TABLE rewards DROP COLUMN IF EXISTS is_flash;
ALTER TABLE rewards DROP COLUMN IF EXISTS tier_id;
DROP TABLE IF EXISTS reward_tiers;
