ALTER TABLE products DROP COLUMN IF EXISTS points_per_scan;
ALTER TABLE tenants DROP COLUMN IF EXISTS scan_quota_per_day;
ALTER TABLE reward_reservations DROP COLUMN IF EXISTS shipping_note;
ALTER TABLE reward_reservations DROP COLUMN IF EXISTS tracking_number;
ALTER TABLE reward_reservations DROP COLUMN IF EXISTS address_id;
ALTER TABLE rewards DROP COLUMN IF EXISTS image_url;
ALTER TABLE rewards DROP COLUMN IF EXISTS delivery_type;
ALTER TABLE scan_history DROP COLUMN IF EXISTS province;
ALTER TABLE scan_history DROP COLUMN IF EXISTS longitude;
ALTER TABLE scan_history DROP COLUMN IF EXISTS latitude;
DROP TABLE IF EXISTS coupon_codes;
DROP TABLE IF EXISTS user_addresses;
ALTER TABLE users DROP COLUMN IF EXISTS last_login_at;
ALTER TABLE users DROP COLUMN IF EXISTS phone_verified;
ALTER TABLE users DROP COLUMN IF EXISTS line_picture_url;
ALTER TABLE users DROP COLUMN IF EXISTS line_display_name;
ALTER TABLE users DROP COLUMN IF EXISTS line_user_id;
ALTER TABLE users DROP COLUMN IF EXISTS avatar_url;
ALTER TABLE users DROP COLUMN IF EXISTS gender;
ALTER TABLE users DROP COLUMN IF EXISTS birth_date;
ALTER TABLE users DROP COLUMN IF EXISTS last_name;
ALTER TABLE users DROP COLUMN IF EXISTS first_name;
